### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by mklabs** [mklabs/tilt#8]
- [x] Routers / Controllers
- [x] React Based view engine
- [x] Vertical or horizontal architecture (http://www.slideshare.net/ChristianHujer/vertical-vs-horizontal-software-architecture-ruby-conf-india-2016-59817161)
- [x] Models ORM using Sequelize
  - [ ] Mongoose
  - [ ] PouchDB
  - [ ] LevelDB
- [x] Asset compiler - Using either browserify or webpack, with ES6/ES7 presets pre-configured.
- [ ] LiveReload - Assets are watched for changes, compiled down when they need to and browsers are notified for changes to dynamically live reload the pages (liveractload, tinylr or browsersync)
- [ ] Error reporting - stylelint / eslint assets. Catch browserify / postcss errors. Format and respond error page (like [play errors](https://www.playframework.com/documentation/2.5.x/resources/manual/working/commonGuide/assets/images/coffeeError.png))
- [ ] A custom REPL is available to inspect and debug the app.
- [ ] Bult-in testing tools - Using supertest / enzyme
- [ ] Simple Dependency Injection using ES7 annotations.
- [ ] client side, reuse routers, views. possibly models.

---

> - Hit refresh workflow - Sources are compiled when they need to and server is restarted automatically using nodemon.
> - console and build tools - A custom REPL is available to inspect and debug your app.
> - Bult-in testing tools - Using supertest, testing controllers output and behavior is really easy. Enzyme provides helpers to test your React views.
> - Yeoman generators and templates to quickly scaffold an entire app, or individual entities.
